services:
  - type: web
    name: blabhear-frontend
    repo: https://github.com/KnowYourLines/blabhear-frontend.git
    env: static
    buildCommand: yarn build
    staticPublishPath: dist
    domains:
      - blabhear.com
    envVars:
      - key: VUE_APP_BACKEND_URL
        fromService:
          name: blabhear-backend
          type: web
          property: hostport

  - type: web
    name: blabhear-backend
    env: python
    repo: https://github.com/KnowYourLines/blabhear-backend.git
    region: ohio
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt; python manage.py makemigrations api; python manage.py migrate"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT server.wsgi:application"
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: DEBUG
        value: False
      - key: LOCAL
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        fromService:
          name: blabhear-backend
          type: web
          property: host
      - key: CORS_ALLOWED_ORIGINS
        value: https://blabhear.com
      - key: DATABASE_URL
        fromDatabase:
          name: blabhear-db
          property: connectionString
      - key: DEEPGRAM_API_KEY
        sync: false

databases:
  - name: blabhear-db
    plan: free
    region: ohio
    postgresMajorVersion: 14
    ipAllowList: [] # only allow internal connections
